name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: 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